/*
** EPITECH PROJECT, 2025
** G-OOP-400-LYN-4-1-tekspice-1
** File description:
** Lexer class declaration
*/

#ifndef NTS_LEXER_HPP_
#define NTS_LEXER_HPP_

#include <string>

namespace nts {

/**
 * @brief Types of tokens that can be generated by the lexer
 */
enum class TokenType {
  CHIPSETS_SECTION,
  LINKS_SECTION,
  IDENTIFIER,
  NUMBER,
  COLON,
  NEWLINE,
  EOF_TOKEN,
  UNKNOWN
};

/**
 * @brief Represents a single token generated by the lexer
 */
struct Token {
  TokenType type;
  std::string value;
  std::size_t line;
  std::size_t col;

  /**
   * @brief Construct a new Token object
   *
   * @param t The type of the token
   * @param v The string value of the token
   * @param l The line number where the token was found
   * @param c The column number where the token was found
   */
  Token(TokenType t, const std::string &v, std::size_t l, std::size_t c)
      : type(t), value(v), line(l), col(c) {}
  /**
   * @brief Construct a new Default Token object (UNKNOWN)
   */
  Token() : type(TokenType::UNKNOWN), value(""), line(0), col(0) {}
};

/**
 * @brief Lexical analyzer for nanoTekSpice configuration files
 */
class Lexer {
public:
  /**
   * @brief Construct a new Lexer object
   *
   * @param input The input string to tokenize
   */
  explicit Lexer(const std::string &input);

  /**
   * @brief Destroy the Lexer object
   */
  ~Lexer() = default;

  Lexer(const Lexer &) = delete;
  Lexer &operator=(const Lexer &) = delete;
  Lexer(Lexer &&) noexcept = default;
  Lexer &operator=(Lexer &&) noexcept = default;

  /**
   * @brief Get the next token from the input
   *
   * @return Token The next token
   */
  Token nextToken();

private:
  std::string _input;
  std::size_t _pos;
  std::size_t _line;
  std::size_t _col;

  char peekChar() const;
  char advanceChar();
  void skipWhitespace();
  void skipComment();
  Token parseIdentifierOrKeyword();
  Token parseNumber();
};

} // namespace nts

#endif /* !NTS_LEXER_HPP_ */
